return {
	Tokenizer = {
		toFormat = "#", -- Prefix before tokenizing | "#H:#M:#S" -> {"#H", "#M", "#S"}

		resultShouldIncludeUnknownTokens = true,
	},

	tokensRequiringFormatting = {
		-- Formatting includes: 0 in front of lonely numbers
		"hour_24",
		"minute",
		"second",
	},

	timesTable = {
		{ "Year", "y", 31536000 },
		{ "Month", "mo", 2628000 },
		{ "Week", "w", 604800 },
		{ "Day", "d", 86400 },
		{ "Hour", "h", 3600 },
		{ "Minute", "m", 60 },
		{ "Second", "s", 1 },
	},

	addOrRemoveTypes = {
		"second",
		"seconds",
		"minute",
		"minutes",
		"hour",
		"hours",
		"day",
		"days",
		"week",
		"weeks",
		"month",
		"months",
		"year",
		"years",
	},

	Patterns = {
		["h"] = { expectedType = "hour_12", Type = "number" },
		["hh"] = { expectedType = "hour_24", Type = "number" },
		["m"] = { expectedType = "minute", Type = "number" },
		["s"] = { expectedType = "second", Type = "number" },
		["ms"] = { expectedType = "millis", Type = "number" },
		["mm"] = { expectedType = "month", Type = "number" },
		["mmm"] = { expectedType = "month_short", Type = "string" },
		["mmmm"] = { expectedType = "month_long", Type = "string" },
		["dd"] = { expectedType = "day_short", Type = "number" },
		["dddd"] = { expectedType = "day_long", Type = "string" },
		["yd"] = { expectedType = "year_day", Type = "number" },
		["myd"] = { expectedType = "max_year_days", Type = "number" },
		["yy"] = { expectedType = "year_short", Type = "number" },
		["yyyy"] = { expectedType = "year_long", Type = "number" },
		["z"] = { expectedType = "timezone", Type = "string" },
		["w"] = { expectedType = "week_day", Type = "number" },
		["ww"] = { expectedType = "week_year", Type = "number" },
		["u"] = { expectedType = "unix", Type = "number" },
		["uu"] = { expectedType = "unix_ms", Type = "number" },
	},

	Names = {
		weekDays = {
			"Sunday",
			"Monday",
			"Tuesday",
			"Wednesday",
			"Thursday",
			"Friday",
			"Saturday",
		},

		Months = {
			"January",
			"February",
			"March",
			"April",
			"May",
			"June",
			"July",
			"August",
			"September",
			"October",
			"November",
			"December",
		},
	},

	Timezones = {
		-- Format: [timeZoneName] = to_add_to_GMT
		-- Types: [string] = number

		["DST"] = -12,
		["HST"] = -10,
		["AKDT"] = -8,
		["PDT"] = -7,
		["PST"] = -8,
		["UMST"] = -7,
		["MDT"] = -6,
		["CAST"] = -6,
		["CDT"] = -5,
		["CCST"] = -6,
		["SPST"] = -5,
		["EST"] = -5,
		["EDT"] = -4,
		["UEDT"] = -5,
		["VST"] = -4.5,
		["PYT"] = -4,
		["ADT"] = -3,
		["CBST"] = -4,
		["SWST"] = -4,
		["PSST"] = -4,
		["NDT"] = -2.5,
		["ESAST"] = -3,
		["AST"] = -3,
		["SEST"] = -3,
		["GDT"] = -3,
		["MST"] = -3,
		["BST"] = -3,
		["CVST"] = -1,
		["UTC"] = 0,
		["GMT"] = 0,
		["GST"] = 0,
		["WEDT"] = 2,
		["CEDT"] = 2,
		["RDT"] = 2,
		["WCAST"] = 1,
		["NST"] = 1,
		["MEDT"] = 3,
		["SDT"] = 3,
		["EEDT"] = 3,
		["SAST"] = 2,
		["FDT"] = 3,
		["TDT"] = 3,
		["JDT"] = 3,
		["LST"] = 2,
		["JST"] = 3,
		["KST"] = 3,
		["EAST"] = 3,
		["MSK"] = 3,
		["SAMT"] = 4,
		["IDT"] = 4.5,
		["GET"] = 4,
		["CST"] = 4,
		["WAST"] = 5,
		["YEKT"] = 5,
		["PKT"] = 5,
		["IST"] = 5.5,
		["SLST"] = 5.5,
		["NCAST"] = 7,
		["NAST"] = 8,
		["MPST"] = 8,
		["TST"] = 8,
		["UST"] = 8,
		["NAEST"] = 8,
		["ACST"] = 9.5,
		["AEST"] = 10,
		["WPST"] = 10,
		["YST"] = 9,
		["CPST"] = 11,
		["NZST"] = 12,
		["FST"] = 12,
		["KDT"] = 13,
		["SST"] = 13,
	},
}
